export enum ActionTypes {
  ADD_WISHES =  'ADD_WISHES',
  REMOVE_WISHES =  'REMOVE_WISHES',
  UPDATE_WISHES =  'UPDATE_WISHES',
  FILTER_WISHES = 'FILTER_WISHES',
  CROSS_OUT_WISHES = 'CROSS_OUT_WISHES',
  REMOVE_ALL_WISHES = 'REMOVE_ALL_WISHES',
}